# ConfigMap : configuration Loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: dani
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /loki

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      aws:
        endpoint: storage-kubernetes.iict-heig-vd.in:9000
        bucketnames: nearai-logs
        region: ch
        access_key_id: ${MINIO_ACCESS_KEY}
        secret_access_key: ${MINIO_SECRET_KEY}
        s3forcepathstyle: true
        insecure: false # HTTPS
        http_config:
          insecure_skip_verify: true # cert auto-signé

    # Rétention : on garde les logs 30 jours (720h), purge gérée par le compactor.
    limits_config:
      retention_period: 720h

    compactor:
      working_directory: /loki/compactor
      delete_request_store: s3
      retention_enabled: true
      retention_delete_delay: 2h
      compaction_interval: 10m
