apiVersion: v1
kind: Pod
metadata:
  name: dog-classifier
  namespace: dani
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  imagePullSecrets:
    - name: ghcr-secret
  containers:
    - name: dog-classifier
      image: ghcr.io/nearai-interreg/ray-wordcount:latest
      imagePullPolicy: Always
      command: ["python3.12", "dog_classifier.py"]
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
