site_name: TB — NEARAI Interreg
docs_dir: docs
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

nav:
  - Journal: journal.md
  - Notes: notes.md
  - Planification: Planification/planification.md
  - Spécifications: Specification/specifications.md
  - SAM3: SAM3/Readme.md
  - Liens: links.md
