apiVersion : v1
kind : Pod
metadata :
  name: sam3-test
  namespace: dani
spec :
  restartPolicy: Never
  runtimeClassName: nvidia
  imagePullSecrets:
    - name: ghcr-secret
  containers :
    - name: sam3-test
      image: ghcr.io/nearai-interreg/sam3-test:latest
      imagePullPolicy: Always
      resources:
        limits:
          nvidia.com/gpu: '1'
        requests:
          nvidia.com/gpu: '1'
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN