{
 "title": "GPU Metrics",
 "tags": [
  "gpu",
  "ray",
  "tb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname_filter", "label": "Hostname filter" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ray : Jobs en cours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ray_running_jobs", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Ray : Actors actifs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ray_gcs_actors_count", "legendFormat": "Actors" }
   ]
  },
  {
   "title": "GPU Utilisation actuelle (gauge)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\".*${hostname_filter}.*\"}",
     "legendFormat": "{{Hostname}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Mean seconds per image",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n    {app=\"sam3-batch\"}\n    |= \"Wall time\"\n    | regexp `Wall time\\s*:\\s*\\d+s \\((?P<secs_per_image>[\\d.]+)s/image\\)`\n    | unwrap secs_per_image [24h]\n  )"
    }
   ]
  },
  {
   "title": "Total pictures in 30 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(sum_over_time(\n    {app=\"sam3-batch\"}\n    |= \"Done\"\n    | regexp `Done: (?P<images>\\d+) images`\n    | unwrap images [29d]\n  ))"
    }
   ]
  },
  {
   "title": "GPU Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\".*$hostname_filter.*\"}",
     "legendFormat": "{{Hostname}} gpu{{gpu}} ({{modelName}})"
    }
   ]
  },
  {
   "title": "N° of detections in 30d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(sum_over_time(  \n    {app=\"sam3-batch\"}\n    |= \"Done\"\n    | regexp `Done: \\d+ images, (?P<detections>\\d+) detections`\n    | unwrap detections [29d]\n  )) "
    }
   ]
  },
  {
   "title": "GPU Mémoire utilisée (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\".*${hostname_filter}.*\"}",
     "legendFormat": "{{Hostname}} gpu{{gpu}} ({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\".*${hostname_filter}.*\"}",
     "legendFormat": "{{Hostname}} gpu{{gpu}} ({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Température (°C)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\".*${hostname_filter}.*\"}",
     "legendFormat": "{{Hostname}} gpu{{gpu}} ({{modelName}})"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{app=\"sam3-batch\"}"
    }
   ]
  }
 ]
}