apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache
  namespace: dani
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 10Gi
