apiVersion: v1
kind: Pod
metadata:
  name: sam3-pipeline
  namespace: dani
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: ghcr-secret
  containers:
    - name: sam3-pipeline
      image: ghcr.io/nearai-interreg/ray-sam3:latest
      imagePullPolicy: Always
      command: ["python3.12", "sam3_pipeline.py"]
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
        - name: IMAGE_PATH
          value: "/app/images/20251211-NeoCapture_S001_Trimblemx50_000001.jpg"
