= Journal de travail <journal-de-travail>
#block[
  #figure(
    align(center)[#table(
      columns: 6,
      align: (left, left, right, right, right, right),
      table.header([Date], [Description], [Rech. \[h\]], [Dev. \[h\]], [Rapport \[h\]], [Admin \[h\]]),
      table.cell(align: right, colspan: 6)[#emph[Le journal de travail continue à la page suivante.];],

      [20.02.2026],
      [Semaine 1 — Kick-off, analyse Ray, MinIO, Label Studio, mise en place Git],
      [4.5],
      [0.5],
      [0],
      [0.5],
      [27.02.2026],
      [Semaine 2 — Analyse alternatives S3, Ray vs Spark vs ZARR, PostGIS, base spécification],
      [5.5],
      [0],
      [1],
      [1.5],
      [06.03.2026],
      [Semaine 3 — Dockerfile SAM3, déploiement K8s, inférence GPU, rédaction spécification Typst],
      [0.5],
      [4],
      [3],
      [2],
      [13.03.2026],
      [Semaine 4 — Dockerfile Ray, WordCount MapReduce, manifestes K8s, classifieur EfficientNet B0 distribué],
      [2],
      [8],
      [0.5],
      [0.5],
      [20.03.2026],
      [Semaine 5 — Restructuration manifestes KubeRay, pipeline sam3\_pipeline.py, Dockerfile.sam3, Typst],
      [1],
      [4.5],
      [2.5],
      [1],
      [27.03.2026],
      [Semaine 6 — Debug pipeline cluster (OOM, libGL), optimisation batch, benchmark 512×512 vs 1024×1024],
      [1],
      [3.5],
      [0],
      [0],
      [03.04.2026],
      [Semaine 7 — Downsampling (0.5×), tests locaux, analyse résultats, réorganisation structure projet],
      [2],
      [4],
      [0],
      [1],
      [10.04.2026], [Semaine 8 — Analyse stack observabilité : Loki, Promtail, DCGM Exporter], [4], [0], [0], [0],
      [17.04.2026],
      [Semaine 9 — Reprise projet, diagramme architecture, debug RayCluster, étude Parquet],
      [5.5],
      [1],
      [1.5],
      [2],
      [24.04.2026],
      [Semaine 10 — Pipeline E2E : Parquet, GPS EXIF, Label Studio, run cluster 40 images, première rédaction rapport],
      [2],
      [8],
      [2.5],
      [0],
      [01.05.2026],
      [Semaine 11 — Stack observabilité déployée (Prometheus, Loki, Promtail, Grafana), run 2000 images, pipeline dynamic],
      [1.5],
      [6.5],
      [1],
      [0],
      [11.05.2026],
      [Semaine 12 — Rapport : DCGM, RayCluster, Kubernetes, Alloy, footnotes, squelette résultats, warning box, Zotero ; lecture Kubernetes/Docker Up and Running + articles (jours fériés)],
      [7],
      [2],
      [18],
      [1],
    )],
    caption: [Journal de travail],
    kind: table,
  )
]
