apiVersion: v1
kind: Service
metadata:
  name: sam3-api
  namespace: dani
  labels:
    app: sam3-api
spec:
  selector:
    app: sam3-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
