apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sam3-api
  namespace: dani
subjects:
  - kind: ServiceAccount
    name: sam3-api
    namespace: dani
roleRef:
  kind: Role
  name: sam3-api
  apiGroup: rbac.authorization.k8s.io
