apiVersion: v1
kind: Service
metadata:
  name: sam3-segment
  namespace: dani
  labels:
    app: sam3-segment
spec:
  selector:
    app: sam3-segment
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
