FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN python3.12 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

# PyTorch CUDA 12.6
RUN pip install torch==2.7.0 torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/cu126

# SAM3
RUN git clone https://github.com/facebookresearch/sam3.git && \
    cd sam3 && \
    pip install ".[notebooks,train,dev]"

# Ray + dépendances pipeline
RUN pip install "ray[data,train,serve,default]==2.54.0" \
    exif \
    Pillow \
    opencv-python-headless \
    "numpy>=1.26,<2"

COPY RAY/sam3_pipeline.py ./
COPY images/ ./images/

CMD ["python3.12", "sam3_pipeline.py"]
