apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:WvYnYZJJv2Q1tVfRBpj/nnr4KgPDPRMzHBYQKyhPknPaAnDzSf8Qjlk0SPQVrslQAYd9ZZTgZz6r5d0P3iCE+dgSSo8u/DFTn4nU2PMExepxguhDKs/e2zfGs8Q53g3UpBUrOp1U2dm+/9bINpbDP6mxj7JqwwQOQke/iQkDFcyUQ/h+FvDN6fVtSwkBxPDIW/XkZxbwKdNSA8rH7/7LHm8LqdrNa72aMQw7lhNoVuUAoDMwQmKa+Q+ou10UT3O6vRbLKap9G9dgzMhZ2Ne8Zl+YnBx3dav1UG4TRImArsgdEvAYTk3lyQ==,iv:8KyvpTA3/FevuUPm4yRpzNd4TyLTJWsrqbTOKKJ0nQQ=,tag:25B/0/Zl2+/mJcsp/wwgKA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: dani
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFMwM1JDUVgzanVlMDJR
            cGtyV0R6VUFSQjJxWkJnQ1hIWVV4RW8zYVRvCnFnWVlvdmtNUkRrR1pBd0pVV0Iy
            dDdLYjd1U2FsS0RZRlk0TWhML09BZjQKLS0tIHNWQjlQQTAxTk1hZVFHYXZySlZ1
            bGFzR05WQkZPSGJEYUs1eHk5NE9qb2cKC2fHXg8qsReNWszIoVR/xZ9MQV0azeKf
            N5iVBscTF1lKAd4Dve+PfS5otwX2VuoeE4OyKk2NeFoREXurWuni6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehjx7983sy8649u4mh5egu35kyd827fn8rvew2rx5kcj6krvsepq37ykml
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T12:20:28Z"
    mac: ENC[AES256_GCM,data:H+tUwUuDVzIL6jvwA9sKTQmhwmO1H5VhIQcLbtUMMExquYpRDUN+k5jLIKRG41HEDIwz+dEaWymPZVYqpxQdskLwcFbNKEi+PT64i7GOoSjOugl8jbQRDrXJsvOGKv/xXFKR8BmzTHrQpjKKm70gXVye0mg5Ic9T01VoIicLQok=,iv:cWzBI62KbQSoVrW7TbqPt7NqthEIEKA7nELmfyLqSV0=,tag:hrTH8LNf9SGKwhRaYxV48A==,type:str]
    version: 3.13.1
