apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: dani
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:Zh6jaAVdXOmwyOH1ymIKlcUlfdFnihBK,iv:UJbfNtg0zKZzm3nrLIPBvT3DOxYNUaKRKcM+2/W1bqI=,tag:Rm8r/4wv5/TDbXQdPlprvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUytzNlZOMnVYbFBHUG9C
            K1FPK0o0dDZQVUpNbm1wVnhLdUhmcFp6Y1dRCk16c05Ub1BwV2J3aS9ER1NuTWxX
            NUxvRVNuWFRJaWdodkQ1OFE2bkZSZDgKLS0tIHZQUytzU2ZXRGlTR0xxWk5hNjBu
            WGR4WVR0NG9Ea1R5RnhmTWlyNUVCMkUKjQ3mevkXFTXIH+Cq6CZXp4ovv8/1Qzmm
            vpf/U/4fPaHRHF6juxEtriEOycnXbSUtNhgAwmDti/FzRY14Av62gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehjx7983sy8649u4mh5egu35kyd827fn8rvew2rx5kcj6krvsepq37ykml
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T08:34:10Z"
    mac: ENC[AES256_GCM,data:RjbdFbHusB9PLRLeQgUBljuGXvIdWw7YQzsh/ux6CZpV4eeYvGHhxQ3rsqARR2NnambehoZSyeJ3SIryFpQ+rbcOpy4INrv2gSnftLcHoPdumVYAHW1jihEO/0xUdlGvZJ1d2hM+4lBVDvsO/Ds79+f0GvPD52K8bTfqwJTHHnM=,iv:r65IzQEtnAmTPS8eIwrb5HAVeCFCA1wvYFuzIHVPdXo=,tag:4ieP+DZeFUxypyieSFokgA==,type:str]
    version: 3.13.1
