apiVersion: v1
kind: Secret
metadata:
    name: hf-secret
    namespace: dani
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:I9pIe/baWw9Iigt0wAlaE/E6D/i8Pwsu+QhMYtlKieWeHdbwsw==,iv:scX8Of5H3sbOi7xNXdMCdIatxx84++tIqCgu7ZmPjkk=,tag:NhVTFnfibJjuiW6Ma2nMYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRm9vMmZGeEFDTkNHZVg4
            enBSMHJ2RWhHdGloNlRJUmYxRzlTVVJhdFE4ClZUNEo0MUFtSkpmNERSMWJEVnc3
            N2hpT1F3enpocURGOFQ4TmUvNWhnUDAKLS0tIEFhcVcvYzUvcGRXSDMwMm9ZT1RW
            a0Z3Tm05ZEJWVVY3aG9Da1YvVFlFakUK9GZTbAvO5mAUD69xDB6hyBCZHXkivWWf
            IEv1B2CAMm4qeU/GfGDoKpg3AXqW+5S7ZjF9/tcKorAHLN3soVlh4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehjx7983sy8649u4mh5egu35kyd827fn8rvew2rx5kcj6krvsepq37ykml
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T09:48:24Z"
    mac: ENC[AES256_GCM,data:JCMztZiD49k5MQemJGkKC4ztqvo8vm68+JLfD1CVbqsy8GBtNQ4mEoBLnmYSP8av/W2g8vqun+i9v8wbP5v775lATWUmOKtqrXef1GB+eCKWY3iTnKKd6iRtKdaE/GWORD1yvYmiNt2kpnaEs6jOrQiGVtNdcrzMQlKwV77TcEE=,iv:V8Ft3z4n9bVZI6kfQWBdHY41hYd0x8uGZrLI8CI9Oo8=,tag:RYPRVuLkha0cUlHBHAwO4w==,type:str]
    version: 3.13.1
