apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: dani
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:DjC2SqT5Vaxsctbg7IH69iX+x6Q=,iv:LQJpwDJ7KGjjN4Q3g4M1ka07sa1pznQSLL5L+xFLCek=,tag:CtX1ce/09LNuOUCQZe6j0Q==,type:str]
    secret_key: ENC[AES256_GCM,data:qduNJEEjNoa5wI4J5fVAqnZKZV23u97bJV+ij+8ahDWj4inTSyf9Wg==,iv:KfEGE8bVY0nW1aR4Oo4wZN1KUHLZ1Pb8QzHLNQE5PpE=,tag:1DksC+9cd3kFLa4kOgmBVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeWlTRTdQelo4eC9sY250
            T3Y2amQ4VHpsb3JacG9Wby9kdDJYa1VSenlnClpmbjh1TmYrMkhXeU5uUk5mQXcv
            elZESGZVRmtKL09PMFMrQW4xOG5YZWMKLS0tIFJSdWE3NHMxYU9WMzB3WVZsYlM5
            RnQ2d2JuVmdRS1NQZXhrUHI5TkxES1kKnM3J4RDX7FKQ9qOwhqwQCFOCJeQOvR7B
            c1S2UcV5EMcDSkoA52mepvHBsLuHsopKS9C3Ko3KjpZHRaEE9FdPCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehjx7983sy8649u4mh5egu35kyd827fn8rvew2rx5kcj6krvsepq37ykml
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T08:44:05Z"
    mac: ENC[AES256_GCM,data:l/aUHHNQapv1l59airtQi/f5vuFiek1UkB1O+RUkSmiMBYVbOy6eoPANK6TZNYNusO+fzED0vg/IngEuRhi9zpA5pf1u6zILo3FPx+F8LcXcP/cgAqwxUkGUmANQOkTphaf0r+NK7zPSA6qx2r4FNl1sWo8qG9f5zVfYIzJ5mi0=,iv:yelRDFlWkbqQLU7WOo1+BdWQGzSW3hHYHWYz+EJt6eI=,tag:i6miR/kfMm8856ktHhRNBg==,type:str]
    version: 3.13.1
